package com.dmdev.jdbc.starter;

import com.dmdev.jdbc.starter.until.ConnectionManager;
import org.postgresql.Driver;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

public class JdbcRunner {
    public static void main(String[] args) throws SQLException {
        Long cost = 200L;
        List<Long> result = getTicketsByCost(cost);
        System.out.println(result);
    }
    private static List<Long> getTicketsByCost(Long cost) throws SQLException{
        String sql= """
                SELECT id
                from ticket
                where cost > ?
                """;
        List<Long> result = new ArrayList<>();
        try (Connection connection = ConnectionManager.open();
        PreparedStatement prepareStatement = connection.prepareStatement(sql)){
            prepareStatement.setLong(1,cost);
            ResultSet resultSet=prepareStatement.executeQuery();
            while (resultSet.next()){
                result.add(resultSet.getObject("id",Long.class));
            }
        }
        return result;
    }

    private static void test() throws SQLException {
        Class<Driver> driverClass = Driver.class;
        String sql = """
                INSERT into info(data)
                values 
                ('autogenerated')
                """;
        try (Connection connection = ConnectionManager.open();
             Statement statement = connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
             ) {
            System.out.println(connection.getSchema());
            System.out.println(connection.getTransactionIsolation());
            int executeResult = statement.executeUpdate(sql,Statement.RETURN_GENERATED_KEYS);
            ResultSet resultSet = statement.getGeneratedKeys();
            if(resultSet.next()){
                int generatedId = resultSet.getInt("id");
                System.out.println(generatedId);
            }

        }
    }
}